version: 2
jobs:
  build:
    working_directory: ~/mcumgr-android
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - run:
           name: Configure Android SDK Licenses
           command: |
             mkdir "$ANDROID_HOME/licenses" || true
             echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
             echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"
      - restore_cache:
          key: gradle-{{ checksum "settings.gradle" }}-{{ checksum "build.gradle" }}-{{ checksum "mcumgr-core/build.gradle" }}-{{ checksum "mcumgr-ble/build.gradle" }}
      - run:
          name: Android Assemble Debug
          command: >
                     ./gradlew
                     -PdisablePreDex
                     --max-workers 2
                     --no-daemon
                     --stacktrace
                     assembleDebug 
      - run:
          name: Import GPG Keys
          command: echo "$SIGNING_SECRET_KEY" | base64 --decode > ~/mcumgr-private.asc && gpg --batch --import ~/mcumgr-private.asc && echo "$SIGNING_PASSWORD" > ~/mcumgr-private-passphrase && gpg --pinentry-mode loopback --passphrase-file ~/mcumgr-private-passphrase --keyring secring.gpg --export-secret-keys > ~/.gnupg/secring.gpg 
      - run:
          name: Deploy
          command: .circleci/deploy.sh
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "settings.gradle" }}-{{ checksum "build.gradle" }}-{{ checksum "mcumgr-core/build.gradle" }}-{{ checksum "mcumgr-ble/build.gradle" }}
      - run:
          name: Test
          command: ./gradlew test
      - run:
          name: JaCoCo Code Coverage Report
          command: ./gradlew jacocoTestDebugUnitTestReport
      - run:
          name: Codecov
          command: bash <(curl -s https://codecov.io/bash)
